Repository outerbase/sdk, pull requests merged in 2024-05, with the labels that each got.

#1 emit types, tweak tsconfig
  tsconfig.json
Labels: enhancement

#6 Support Column decorators
  README.md
  src/client.ts
  src/generators/generate-models.ts
  src/generators/model-template.handlebars
  src/index.ts
  src/models/decorators.ts
  src/models/index.ts
  tsconfig.json
Labels: enhancement

#9 Add a Cloudflare D1 connection
  playground/.gitignore
  playground/index.js
  playground/package.json
  src/client.ts
  src/connections/cloudflare.ts
  src/index.ts
Labels: enhancement

#12 Reverting Client updates from a bad merge
  README.md
  package.json
  src/client.ts
  src/connections/cloudflare.ts
  src/connections/index.ts
Labels: bug, documentation

#14 Fix missing undefined in function input
  package.json
  src/connections/cloudflare.ts
  src/connections/index.ts
  src/connections/outerbase.ts
Labels: bug

#2 TSConfig and README updates
  README.md
Labels: documentation

#29 Trigger prettier formatting on git commit hook
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
  src/connections/cloudflare.ts
  src/connections/outerbase.ts
  src/generators/generate-models.ts
Labels: enhancement

#21 Support .toString() in query builder
  .github/workflows/test.yml
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  playground/index.js
  src/client.ts
  src/connections/cloudflare.ts
  src/connections/index.ts
  src/connections/outerbase.ts
  src/query-params.ts
  src/query.ts
  tests/connections/cloudflare.test.ts
  tests/connections/outerbase.test.ts
  tests/generators/generate-models.test.ts
  tests/query-params.test.ts
  tests/query.test.ts
  tests/to-string.test.ts
  tsconfig.json
Labels: enhancement
